services:
  - type: web
    name: pulse-of-india
    runtime: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: CLICKHOUSE_HOST
        sync: false
      - key: CLICKHOUSE_PORT
        value: "8443"
      - key: CLICKHOUSE_USER
        sync: false
      - key: CLICKHOUSE_PASSWORD
        sync: false
      - key: CLICKHOUSE_DATABASE
        value: "default"
      - key: AMP_CONTENT_CHART_ID
        value: "0g3tnaix"
